config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  resources :follow, :controller => 'friendships'
  resources :profiles

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user

  scope :latests, lambda { order(updated_at: :desc)}
  def self.all_users_profiles_hash
    User.all.map do |u|
      {
        id: u.id,
        created_at: u.created_at,
        last_sign_in_at: u.last_sign_in_at,
        name: u.name,
        email: u.email,
        profiles: u.profiles.map(&:attributes)
      }
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  include Amistad::FriendModel

  has_many :profiles

  # accepts_nested_attributes_for :profiles, reject_if: :all_blank

  #TODO: should delegete profile desc to user and

  def desc
    profiles.latests.first
  end

  def self.others current_user
    if current_user.present?
      User.where.not(id: current_user.id)
    else
      User.all
    end
  end

  def display_name
    name || email
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def after_sign_out_path_for(resource_or_scope)
    root_path
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @friends = current_user.friends
  end

  def create
    invitee = User.find_by_id(params[:user_id])
    current_user.invite invitee
    render :json => {result: invitee.approve(current_user), user: current_user}
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @other_users = User.others(current_user)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  #TODO: move this json API to another place and add versioning, maybe try https://github.com/Sutto/rocket_pants
  def index
    @profiles = Profile.where(user_id: params[:id]).order(updated_at: :desc)
    respond_to do |format|
      format.html { render text: "not supported"}
      format.json { render json: {response: Profile.all_users_profiles_hash }}
    end
  end

  def show
    @user = User.find(params[:id])
    @profiles = Profile.where(user_id: params[:id]).latests
    json_data = { profiles: @profiles.map(&:attributes),  profile_count: @profiles.size }
    respond_to do |format|
      format.html
      format.json { render json: { response: json_data }}
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/friendships/index.html.slim
h1
  = current_user.try(:display_name)
  | 关注的人

.row
  ul
    - @friends.each do |user|
      li
        = user.display_name
        a.profile-link href=(profile_path(user.id)) 个人资料

app/views/home/index.html.slim
h1
  |欢迎 &nbsp;
  = current_user.try(:display_name)
p 欢迎来到  Followme 社区，在这里你将找到很多和你兴趣相投的朋友!!

.row
  ul
    - @other_users.each do |user|
      li
        = user.display_name
        a.profile-link href=(profile_path(user.id)) 个人资料
        - if current_user && !current_user.try(:friends).try{|x| x.include?(user) }
          a.follow-btn.button data={uid: user.id} href="/follow"
            | Follow

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>A Demo App for lilishuo</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <nav class="top-bar" data-topbar role="navigation">
      <ul class="title-area">
        <li class="name">
          <h1><a href="/">FollowMe</a></h1>
        </li>
      </ul>

      <section class="top-bar-section">
        <ul class="right">
          <% if current_user %>
            <li><a href="">Welcome, <%= current_user.try(:display_name) %></a></li>
            <li><a href="<%= destroy_session_path(:user) %>">Sign Out</a></li>
          <% else %>
            <li><a href="<%= new_session_path(:user) %>">Sign In</a></li>
            <li><a href="<%= new_registration_path(:user) %>">Sign up</a></li>
          <% end %>
        </ul>
      </section>
    </nav>

    <div class="container row">
      <%= yield %>
    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/profiles/show.html.slim
h1
  = @user.try(:display_name)
  | 的个人资料

.row
  ul
    - @profiles.each do |p|
      li = p.desc

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>